migrations

diff --git a/docker/app/Dockerfile b/docker/app/Dockerfile
--- a/docker/app/Dockerfile
+++ b/docker/app/Dockerfile
@@ -8,26 +8,30 @@ COPY go.mod ./
 COPY go.sum ./
 RUN go mod download
 
-RUN go get github.com/lib/pq
-RUN go get gopkg.in/yaml.v3
-# Копируем исходный
+RUN go mod tidy
 
-# Копируем исходный код
 COPY . .
 
-# Собираем бинарник
 RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/main ./cmd/main.go
+
 COPY config /app/config
+COPY migrations /migrations
+
+RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xz \
+    && mv migrate /usr/local/bin/migrate
+
 # Stage 2: Создание финального образа
 FROM alpine:latest
 
 WORKDIR /app
 
-# Устанавливаем необходимые утилиты
 RUN apk add --no-cache bash
 
-# Копируем бинарник из первого этапа
 COPY --from=builder /app/main .
 COPY --from=builder /app/config /app/config
+COPY --from=builder /migrations /migrations
+RUN test -d /migrations || (echo "Migrations directory not found" && exit 1)
+COPY --from=builder /usr/local/bin/migrate /usr/local/bin/migrate
+
 # Запускаем приложение
 CMD ["./main"]
